### ISSUE TITLE
[Suggestion] Adding support for other apps

### ISSUE THREAD

**Issue by Popat0** [shusaura85/teraproxy-launcher#1]
It could be interesting to have an option to add more executables starting at the same as tera, with an option to run them elevated or not.
For example, Shinrameter or TCC.

**Comment by shusaura85** [comment]
I'll look to see what's the best method to do this.
The simplest way would be to add more predefined app "slots" that can be filled with what app you want.
The more complex way would be "unlimited slots" that would allow to start an arbitrary number of apps.

I'll think about it and will release an update by the end of the week

**Comment by shusaura85** [comment]
Pushed v2.0 to master and Releases. You can now start any number of apps you want.
Duplicate the ini section for the proxy or game, rename the section and fill it with the info you need.
Apps are started in the order they are inside the ini (except Tera that is always started last)
